[project]
name = "demo-app"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "prometheus-client>=0.22.0",
    "uvicorn[standard]>=0.34.2",
]
